"""add remarks policy model

Revision ID: 211b14fc97ae
Revises: 5c7bc66afd9b
Create Date: 2024-07-03 16:02:16.456731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '211b14fc97ae'
down_revision: Union[str, None] = '5c7bc66afd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'remarks')
    # ### end Alembic commands ###
