"""Create policy model

Revision ID: 5c7bc66afd9b
Revises: 
Create Date: 2024-07-03 15:43:34.838248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c7bc66afd9b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_number', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('policy_cover', sa.Integer(), nullable=False),
    sa.Column('policy_status', sa.String(length=25), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=True),
    sa.Column('medical_type', sa.String(length=25), nullable=True),
    sa.Column('medical_status', sa.String(length=25), nullable=True),
    sa.Column('policy_type', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
