"""add created_at field to policy model

Revision ID: 901a9aa4004f
Revises: 211b14fc97ae
Create Date: 2024-07-03 17:01:09.976415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '901a9aa4004f'
down_revision: Union[str, None] = '211b14fc97ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policies', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policies', 'created_at')
    # ### end Alembic commands ###
